SET LINK_DIR=%1

SHIFT

SET LINK_NAME=%1

SHIFT

SET LINK_FILES=

:ARG_LOOP
IF "%1"=="" GOTO :END_ARG_LOOP
SET LINK_FILES=%LINK_FILES% %1
SHIFT
GOTO :ARG_LOOP

:END_ARG_LOOP

link.exe /OPT:REF /DEBUG /OUT:"%LINK_DIR%\%LINK_NAME%.exe" /MAP:"%LINK_DIR%\%LINK_NAME%.map" %LINK_FILES%
